version: "3.2"

services:
  mtfh-data-landing:
    image: mtfh-data-landing
    build:
      context: .
      dockerfile: MTFHDataLanding/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    environment:
     - ENVIRONMENT=LocalDevelopment
     - AWS_REGION=eu-west-2
     - AWS_ACCESS_KEY_ID=local
     - AWS_SECRET_ACCESS_KEY=local

  mtfh-data-landing-test:
    image: mtfh-data-landing-test
    build:
      context: .
      dockerfile: MTFHDataLanding.Tests/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    environment:
      - ENVIRONMENT=LocalDevelopment
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      
  localstack-s3:
    image: localstack/localstack:latest
    container_name: localstack-s3
    environment:
     - SERVICES=s3
     - DEFAULT_REGION=eu-west-2
     - DATA_DIR=/tmp/localstack/data
    ports:
     - "4566:4566"
    volumes:
      - localstack-data:/tmp/localstack
  
volumes:

    localstack-data:
      name: localstack-data
      
