version: "3.2"

services:
  mtfh-data-landing:
    image: mtfh-data-landing
    build:
      context: .
      dockerfile: MTFHDataLanding/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    environment:
     - ENVIRONMENT=LocalDevelopment
     - DynamoDb_LocalMode=true
     - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
     - AWS_REGION=eu-west-2
     - AWS_ACCESS_KEY_ID=local
     - AWS_SECRET_ACCESS_KEY=local

  mtfh-data-landing-test:
    image: mtfh-data-landing-test
    build:
      context: .
      dockerfile: MTFHDataLanding.Tests/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    environment:
      - ENVIRONMENT=LocalDevelopment
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
  localstack:
    container_name: localstack
    image: localstack/localstack    
    hostname: awslocal    
    ports:
      - "4566:4566"      
    environment:
      - SERVICES=s3
      - DEBUG=1                  
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack      
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      
